# Generated by Django 5.1.1 on 2024-09-11 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyExchangeHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('foundation_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField()),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_rates', to='analyzer.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_rates', to='analyzer.currency')),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LogisticProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=50)),
                ('currency_exchange_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='analyzer.currencyexchangehouse')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.processtype')),
            ],
        ),
        migrations.CreateModel(
            name='GenerativeAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('training_date', models.DateField()),
                ('accuracy', models.FloatField(help_text='Percentage of model accuracy in process optimization')),
                ('used_in_processes', models.ManyToManyField(related_name='ai_models', to='analyzer.logisticprocess')),
            ],
        ),
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficiency_improvement', models.FloatField(help_text='Percentage of improvement in operational efficiency')),
                ('cost_reduction', models.FloatField(help_text='Percentage of reduction in operational costs')),
                ('processing_time_reduction', models.FloatField(help_text='Percentage of reduction in processing time')),
                ('implementation_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('logistic_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='analyzer.logisticprocess')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=50)),
                ('date', models.DateField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('optimization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='analyzer.optimization')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('details', models.TextField()),
                ('created_by', models.CharField(max_length=100)),
                ('logistic_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analyzer.logisticprocess')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.exchangerate')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transactions', to='analyzer.currency')),
                ('logistic_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='analyzer.logisticprocess')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transactions', to='analyzer.currency')),
            ],
        ),
    ]
