# Generated by Django 5.1.1 on 2024-09-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('from_currency', 'to_currency', 'date'), name='unique_exchange_rate'),
        ),
    ]
